"""Python entry point invoked by the `tools/papaia-ctl` bash dispatcher.

Bash owns interactive prompting (per the issue's stated split: "bash
handles arg-parsing, interactive prompts and docker compose calls; Python
handles all YAML / JSON / env / secret manipulation"). The flow is:

  1. bash calls `defaults` to learn sticky/derived values for its prompts.
  2. bash prompts the user (or reads flags / sticky values straight through
     in --non-interactive mode) and resolves every value itself.
  3. bash calls `setup` with the fully-resolved flags; this module never
     blocks on stdin -- it raises SetupError (exit code 3) if something
     required is still missing.

Invoked as `python3 -m lib.cli <subcommand> ...` with `tools/` on
PYTHONPATH (the bash dispatcher sets this up). Addon command handlers live
in cli_addon.py; this module keeps the parser, the dispatch, and the core
setup/render commands.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import (
    cli_addon,
    defaults,
    deployment,
    envtree,
    gen_override,
    render_core,
    reporting,
    resolve,
    secrets,
)


def _tristate(value: str | None) -> bool | None:
    if value is None:
        return None
    return value == "true"


def cmd_defaults(args: argparse.Namespace) -> int:
    """Print sticky/derived values as shell-safe KEY=VALUE lines, one per
    line, so the bash dispatcher can read them without a JSON parser."""
    out = defaults.compute_defaults(Path(args.config_dir), Path(args.repo_root))
    for key, value in out.items():
        print(f"{key}={value}")
    return 0


def cmd_setup(args: argparse.Namespace) -> int:
    repo_root = Path(args.repo_root)
    config_dir = Path(args.config_dir)

    fresh_init = not (config_dir / ".env").is_file()
    envtree.init(config_dir, repo_root, env_name=args.env, force=False)

    tree = envtree.load_config_dir_tree(config_dir, repo_root)
    setup_args = resolve.SetupArgs(
        config_dir=config_dir,
        env_name=args.env,
        host_ip=args.host_ip,
        app_host=args.app_host,
        auth_host=args.auth_host,
        librechat_host=args.librechat_host,
        localai_host=args.localai_host,
        manager_host=args.manager_host,
        npm_admin_host=args.npm_admin_host,
        auth_provider=args.auth_provider,
        oidc_issuer=args.oidc_issuer,
        reverse_proxy_provider=args.reverse_proxy_provider or None,
        external_reverse_proxy=_tristate(args.external_reverse_proxy),
        enable_web_search=_tristate(args.enable_web_search),
        enable_local_ai=_tristate(args.enable_local_ai),
        reranker_model=args.reranker_model or None,
        allow_direct_port_access=args.allow_direct_port_access,
        non_interactive=True,
        force=args.force,
        fresh_init=fresh_init,
    )

    effective_auth_provider = args.auth_provider or tree.get("", {}).get(
        "AUTH_PROVIDER", "internal_keycloak"
    )

    seed = envtree.load_seed_tree(repo_root)
    try:
        # Runs first: write_env_file appends any tree key missing from the
        # shipped template under a "generated by papaia-ctl" banner, so a
        # renamed or dropped key would otherwise be re-emitted on every run.
        tree = resolve.migrate_env_keys(tree)
        tree = secrets.generate_missing_secrets(
            tree, seed, force=args.force, auth_provider=effective_auth_provider
        )
        tree = resolve.resolve_multi_env(tree, setup_args)
        tree = resolve.resolve_hostnames(tree, setup_args)
        tree = resolve.resolve_reverse_proxy(tree, setup_args)
        tree = resolve.migrate_web_search_profiles(tree)
        tree = resolve.resolve_web_search(tree, setup_args)
        tree = resolve.resolve_local_ai(tree, setup_args)
        tree = resolve.resolve_reranker_model(tree, setup_args)
    except resolve.SetupError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3

    tree = envtree.stamp_platform_version(tree, repo_root)
    tree = envtree.stamp_config_dir(tree, config_dir)
    envtree.persist_tree(tree, config_dir, repo_root)
    deployment.sync_manifest(config_dir, tree, repo_root)

    render_core.render(config_dir, repo_root)
    gen_override.generate_overrides(config_dir, repo_root)
    gen_override.generate_ssl_cert_override(config_dir, effective_auth_provider)
    gen_override.generate_addon_ssl_cert_overrides(config_dir, effective_auth_provider, repo_root)

    envtree.write_run_summary(config_dir, tree, fresh_init=fresh_init, force=args.force)
    print(
        "Setup complete. Run 'papaia-ctl start' to bring up the stack."
        f" PAPAIA_CONFIG_DIR={config_dir}"
    )
    if effective_auth_provider == "external_oidc":
        reporting.print_external_oidc_checklist(config_dir, tree)
    return 0


def cmd_materialize(args: argparse.Namespace) -> int:
    envtree.materialize_core_env(Path(args.config_dir), Path(args.repo_root))
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    config_dir = Path(args.config_dir)
    repo_root = Path(args.repo_root)
    render_core.render(config_dir, repo_root)
    gen_override.generate_overrides(config_dir, repo_root)
    tree = envtree.load_config_dir_tree(config_dir, repo_root)
    auth_provider = tree.get("", {}).get("AUTH_PROVIDER", "internal_keycloak")
    gen_override.generate_ssl_cert_override(config_dir, auth_provider)
    gen_override.generate_addon_ssl_cert_overrides(config_dir, auth_provider, repo_root)
    print("Rendered.")
    return 0


def cmd_override_external_nets(args: argparse.Namespace) -> int:
    """Print the external network names declared in one override file
    (one per line). Used by the bash dispatcher to skip overrides whose
    addon networks don't exist yet."""
    for net in gen_override.external_networks(Path(args.file)):
        print(net)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="papaia-ctl-py")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--config-dir", required=True)
    sub = parser.add_subparsers(dest="command", required=True)

    p_materialize = sub.add_parser("materialize-core")
    p_materialize.set_defaults(func=cmd_materialize)

    p_defaults = sub.add_parser("defaults")
    p_defaults.set_defaults(func=cmd_defaults)

    p_setup = sub.add_parser("setup")
    p_setup.add_argument("--env", default="papaia")
    p_setup.add_argument("--host-ip")
    p_setup.add_argument("--app-host")
    p_setup.add_argument("--auth-host")
    p_setup.add_argument("--librechat-host")
    p_setup.add_argument("--localai-host")
    p_setup.add_argument("--manager-host")
    p_setup.add_argument("--npm-admin-host")
    p_setup.add_argument(
        "--auth-provider", choices=["internal_keycloak", "external_oidc"], default=None
    )
    p_setup.add_argument("--oidc-issuer")
    p_setup.add_argument(
        "--reverse-proxy-provider",
        choices=["internal_nginx", "external_proxy", "no_proxy"],
        default=None,
    )
    p_setup.add_argument("--external-reverse-proxy", choices=["true", "false"], default=None)
    p_setup.add_argument("--enable-web-search", choices=["true", "false"], default=None)
    p_setup.add_argument("--enable-local-ai", choices=["true", "false"], default=None)
    p_setup.add_argument("--reranker-model", default=None)
    p_setup.add_argument("--allow-direct-port-access", action="store_true")
    p_setup.add_argument("--force", action="store_true")
    p_setup.set_defaults(func=cmd_setup)

    p_render = sub.add_parser("render")
    p_render.set_defaults(func=cmd_render)

    p_addon_install = sub.add_parser("addon-install")
    p_addon_install.add_argument("--name", required=True)
    p_addon_install.add_argument("--path", default=None)
    p_addon_install.add_argument("--version", default=None)
    p_addon_install.add_argument("--force", action="store_true")
    p_addon_install.set_defaults(func=cli_addon.cmd_addon_install)

    p_addon_start = sub.add_parser("addon-start")
    p_addon_start.add_argument("--name", required=True)
    p_addon_start.add_argument("--force", action="store_true")
    p_addon_start.set_defaults(func=cli_addon.cmd_addon_start)

    p_addon_check = sub.add_parser("addon-check")
    p_addon_check.add_argument("--target-core", default=None)
    p_addon_check.add_argument("--target-version", default=None)
    p_addon_check.add_argument("--target-addon-api", type=int, default=None)
    p_addon_check.add_argument("--target-min-addon-api", type=int, default=None)
    p_addon_check.add_argument("--json", action="store_true")
    p_addon_check.add_argument("--force", action="store_true")
    p_addon_check.set_defaults(func=cli_addon.cmd_addon_check)

    p_addon_remove = sub.add_parser("addon-remove")
    p_addon_remove.add_argument("--name", required=True)
    p_addon_remove.set_defaults(func=cli_addon.cmd_addon_remove)

    p_addon_uninstall = sub.add_parser("addon-uninstall")
    p_addon_uninstall.add_argument("--name", required=True)
    p_addon_uninstall.set_defaults(func=cli_addon.cmd_addon_uninstall)

    p_addon_networks = sub.add_parser("addon-networks")
    p_addon_networks.set_defaults(func=cli_addon.cmd_addon_networks)

    p_active_addons = sub.add_parser("active-addons")
    p_active_addons.set_defaults(func=cli_addon.cmd_active_addons)

    p_override_nets = sub.add_parser("override-external-nets")
    p_override_nets.add_argument("--file", required=True)
    p_override_nets.set_defaults(func=cmd_override_external_nets)

    p_addon_path = sub.add_parser("addon-path")
    p_addon_path.add_argument("--name", required=True)
    p_addon_path.set_defaults(func=cli_addon.cmd_addon_path)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
