"""Python entry point invoked by the `tools/papaia-ctl` bash dispatcher.

Bash owns interactive prompting (per the issue's stated split: "bash
handles arg-parsing, interactive prompts and docker compose calls; Python
handles all YAML / JSON / env / secret manipulation"). The flow is:

  1. bash calls `defaults` to learn sticky/derived values for its prompts.
  2. bash prompts the user (or reads flags / sticky values straight through
     in --non-interactive mode) and resolves every value itself.
  3. bash calls `setup` with the fully-resolved flags; this module never
     blocks on stdin -- it raises SetupError (exit code 3) if something
     required is still missing.

Invoked as `python3 -m lib.cli <subcommand> ...` with `tools/` on
PYTHONPATH (the bash dispatcher sets this up). Addon command handlers live
in cli_addon.py; this module keeps the parser, the dispatch, and the core
setup/render commands.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import (
    backup,
    cli_addon,
    common,
    defaults,
    deployment,
    envtree,
    gen_override,
    gpu_detect,
    migrations,
    npm_provision,
    render_core,
    reporting,
    resolve,
    secrets,
    upgrade,
)


def _tristate(value: str | None) -> bool | None:
    if value is None:
        return None
    return value == "true"


def cmd_defaults(args: argparse.Namespace) -> int:
    """Print sticky/derived values as shell-safe KEY=VALUE lines, one per
    line, so the bash dispatcher can read them without a JSON parser."""
    out = defaults.compute_defaults(Path(args.config_dir), Path(args.repo_root))
    for key, value in out.items():
        print(f"{key}={value}")
    return 0


def cmd_localai_variants(args: argparse.Namespace) -> int:
    """Print the detected LocalAI image variants as shell-safe KEY=VALUE lines.

    Kept out of `defaults` on purpose: this probe forks nvidia-smi and docker,
    while `defaults` runs on every single papaia-ctl setup invocation. The
    wizard calls it only when it is about to ask the question."""
    for key, value in gpu_detect.detection_vars(gpu_detect.detect()).items():
        print(f"{key}={value}")
    return 0


def cmd_setup(args: argparse.Namespace) -> int:
    repo_root = Path(args.repo_root)
    config_dir = Path(args.config_dir)

    fresh_init = not (config_dir / ".env").is_file()
    envtree.init(config_dir, repo_root, env_name=args.env, force=False)

    tree = envtree.load_config_dir_tree(config_dir, repo_root)
    setup_args = resolve.SetupArgs(
        config_dir=config_dir,
        env_name=args.env,
        host_ip=args.host_ip,
        app_host=args.app_host,
        auth_host=args.auth_host,
        librechat_host=args.librechat_host,
        litellm_host=args.litellm_host,
        localai_host=args.localai_host,
        manager_host=args.manager_host,
        npm_admin_host=args.npm_admin_host,
        auth_provider=args.auth_provider,
        oidc_issuer=args.oidc_issuer,
        reverse_proxy_provider=args.reverse_proxy_provider or None,
        external_reverse_proxy=_tristate(args.external_reverse_proxy),
        enable_web_search=_tristate(args.enable_web_search),
        enable_local_ai=_tristate(args.enable_local_ai),
        localai_variant=args.localai_variant or None,
        enable_manager=_tristate(args.enable_manager),
        reranker_model=args.reranker_model or None,
        allow_direct_port_access=args.allow_direct_port_access,
        non_interactive=True,
        force=args.force,
        fresh_init=fresh_init,
    )

    effective_auth_provider = args.auth_provider or tree.get("", {}).get(
        "AUTH_PROVIDER", "internal_keycloak"
    )

    seed = envtree.load_seed_tree(repo_root)
    try:
        # Runs first: write_env_file appends any tree key missing from the
        # shipped template under a "generated by papaia-ctl" banner, so a
        # renamed or dropped key would otherwise be re-emitted on every run.
        tree = resolve.migrate_env_keys(tree)
        tree = secrets.generate_missing_secrets(
            tree, seed, force=args.force, auth_provider=effective_auth_provider
        )
        tree = resolve.resolve_multi_env(tree, setup_args)
        tree = resolve.resolve_hostnames(tree, setup_args)
        tree = resolve.resolve_reverse_proxy(tree, setup_args)
        tree = resolve.migrate_web_search_profiles(tree)
        tree = resolve.resolve_web_search(tree, setup_args)
        tree = resolve.resolve_local_ai(tree, setup_args)
        tree = resolve.resolve_localai_variant(tree, setup_args)
        tree = resolve.resolve_manager(tree, setup_args)
        tree = resolve.resolve_reranker_model(tree, setup_args)
    except resolve.SetupError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3

    tree = envtree.stamp_platform_version(tree, repo_root)
    tree = envtree.stamp_config_dir(tree, config_dir)
    tree = envtree.stamp_workspace_dir(tree, repo_root)
    # After stamp_workspace_dir: the derived default is <workspace>/backup.
    tree = envtree.stamp_backup_dir(tree, override=args.backup_dir)
    tree = envtree.stamp_docker_gid(tree)
    tree = envtree.stamp_host_uid_gid(tree)
    envtree.persist_tree(tree, config_dir, repo_root)
    deployment.sync_manifest(config_dir, tree, repo_root)

    render_core.render(config_dir, repo_root)
    gen_override.generate_overrides(config_dir, repo_root)
    gen_override.generate_ssl_cert_override(config_dir, effective_auth_provider)
    gen_override.generate_addon_ssl_cert_overrides(config_dir, effective_auth_provider, repo_root)
    gen_override.generate_localai_gpu_override(
        config_dir, repo_root, tree.get("", {}).get("LOCALAI_IMAGE_VARIANT", "")
    )

    envtree.write_run_summary(config_dir, tree, fresh_init=fresh_init, force=args.force)
    print(
        "Setup complete. Run 'papaia-ctl start' to bring up the stack."
        f" PAPAIA_CONFIG_DIR={config_dir}"
    )
    if effective_auth_provider == "external_oidc":
        reporting.print_external_oidc_checklist(config_dir, tree)
    return 0


def cmd_materialize(args: argparse.Namespace) -> int:
    envtree.materialize_core_env(Path(args.config_dir), Path(args.repo_root))
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    config_dir = Path(args.config_dir)
    repo_root = Path(args.repo_root)
    render_core.render(config_dir, repo_root)
    gen_override.generate_overrides(config_dir, repo_root)
    tree = envtree.load_config_dir_tree(config_dir, repo_root)
    auth_provider = tree.get("", {}).get("AUTH_PROVIDER", "internal_keycloak")
    gen_override.generate_ssl_cert_override(config_dir, auth_provider)
    gen_override.generate_addon_ssl_cert_overrides(config_dir, auth_provider, repo_root)
    # Also regenerated here, not just in cmd_setup: `papaia-ctl start` renders
    # before bringing the stack up, so a stale override would otherwise survive
    # both an upgrade and a variant change.
    gen_override.generate_localai_gpu_override(
        config_dir, repo_root, tree.get("", {}).get("LOCALAI_IMAGE_VARIANT", "")
    )
    print("Rendered.")
    return 0


def cmd_override_external_nets(args: argparse.Namespace) -> int:
    """Print the external network names declared in one override file
    (one per line). Used by the bash dispatcher to skip overrides whose
    addon networks don't exist yet."""
    for net in gen_override.external_networks(Path(args.file)):
        print(net)
    return 0


def cmd_npm_provision(args: argparse.Namespace) -> int:
    config_dir = Path(args.config_dir)
    repo_root = Path(args.repo_root)
    tree = envtree.load_config_dir_tree(config_dir, repo_root)
    if not npm_provision.provision_npm_hosts(tree):
        return 1
    return 0


# ─────────────────────────────────────────────────────────────────────────
# backup / restore
#
# Output is TSV so the bash dispatcher can consume it with `read` and without
# a JSON parser -- same contract as override-external-nets above.
# ─────────────────────────────────────────────────────────────────────────


def _fail(exc: Exception) -> int:
    print(f"ERROR: {exc}", file=sys.stderr)
    return 3


def _resolve_backup_dir(config_dir: Path, override: str | None) -> Path:
    """--backup-dir wins; otherwise PAPAIA_BACKUP_DIR from the config bundle's
    root .env, which setup stamps as <PAPAIA_WORKSPACE_DIR>/backup."""
    if override:
        return Path(override).expanduser()
    value = common.parse_env_file(config_dir / ".env").get("PAPAIA_BACKUP_DIR", "")
    if not value or common.is_placeholder(value):
        raise backup.BackupError(
            "PAPAIA_BACKUP_DIR is not set in the root .env. Pass --backup-dir=PATH,"
            " or re-run 'papaia-ctl setup --backup-dir=PATH'."
        )
    return Path(value).expanduser()


def cmd_backup_dir(args: argparse.Namespace) -> int:
    try:
        print(_resolve_backup_dir(Path(args.config_dir), args.backup_dir))
    except backup.BackupError as exc:
        return _fail(exc)
    return 0


def cmd_backup_plan(args: argparse.Namespace) -> int:
    config_dir = Path(args.config_dir)
    try:
        backup_dir = _resolve_backup_dir(config_dir, args.backup_dir)
        existing = backup.parse_existing_volumes(
            Path(args.existing_volumes) if args.existing_volumes else None
        )
        plan = backup.build_plan(
            config_dir, Path(args.repo_root), backup_dir, existing=existing
        )
        common.ensure_dir(plan.snapshot / "volumes")
        common.ensure_dir(plan.snapshot / "binds")
        backup.write_plan(plan)
    except backup.BackupError as exc:
        return _fail(exc)
    for name in plan.skipped:
        print(f"WARNING: declared volume does not exist, skipping: {name}", file=sys.stderr)
    print(f"SNAPSHOT\t{plan.snapshot}")
    for artifact in plan.artifacts:
        print(f"{artifact.kind}\t{artifact.archive}\t{artifact.source}\t{artifact.owner}")
    return 0


def cmd_backup_finish(args: argparse.Namespace) -> int:
    snapshot = Path(args.snapshot)
    try:
        backup_dir = _resolve_backup_dir(Path(args.config_dir), args.backup_dir)
        plan = backup.read_plan(snapshot)
        manifest = backup.write_manifest(
            snapshot,
            plan,
            backup.read_results(snapshot),
            papaia_version=envtree.resolve_platform_version(Path(args.repo_root)),
        )
        entry = backup.record_backup(backup_dir, plan, manifest, args.result)
    except backup.BackupError as exc:
        return _fail(exc)
    # Intermediate state; the manifest supersedes it. results.tsv stays as the
    # audit trail of which archives failed.
    (snapshot / backup.PLAN_NAME).unlink(missing_ok=True)
    print(f"ID\t{entry['id']}")
    print(f"SIZE_MB\t{entry['size_mb']}")
    print(f"ARTIFACTS\t{entry['artifacts']}")
    return 0


def cmd_backup_prune(args: argparse.Namespace) -> int:
    try:
        backup_dir = _resolve_backup_dir(Path(args.config_dir), args.backup_dir)
        removed = backup.prune(backup_dir, args.retention_period_days)
    except backup.BackupError as exc:
        return _fail(exc)
    for backup_id in removed:
        print(backup_id)
    return 0


def cmd_backup_list(args: argparse.Namespace) -> int:
    try:
        backup_dir = _resolve_backup_dir(Path(args.config_dir), args.backup_dir)
        index = backup.load_index(backup_dir)
    except backup.BackupError as exc:
        return _fail(exc)
    backups = index.get("backups") or []
    if not backups:
        print(f"No restore points recorded in {backup_dir}.")
        return 0
    print(f"Restore points in {backup_dir}:")
    print(f"  {'ID':<21} {'CREATED (UTC)':<21} {'SIZE (MB)':>10}  RESULT")
    for entry in sorted(backups, key=lambda b: str(b.get("created_at", ""))):
        print(
            f"  {str(entry.get('id', '')):<21}"
            f" {str(entry.get('created_at', '')):<21}"
            f" {str(entry.get('size_mb', '')):>10}"
            f"  {entry.get('result', '')}"
        )
    return 0


def cmd_backup_delete(args: argparse.Namespace) -> int:
    # --restore-point is repeatable, and each value may itself be a
    # comma-separated list -- bash passes one flag per id, an operator may do
    # either.
    ids: list[str] = []
    for chunk in args.restore_point or []:
        ids.extend(part.strip() for part in chunk.split(",") if part.strip())
    try:
        backup_dir = _resolve_backup_dir(Path(args.config_dir), args.backup_dir)
        removed = backup.delete_backups(backup_dir, ids)
    except backup.BackupError as exc:
        return _fail(exc)
    for backup_id in removed:
        print(backup_id)
    return 0


def cmd_restore_resolve(args: argparse.Namespace) -> int:
    config_dir = Path(args.config_dir)
    try:
        backup_dir = _resolve_backup_dir(config_dir, args.backup_dir)
        entry, warnings = backup.resolve_restore_point(backup_dir, args.restore_point)
        snapshot = backup.snapshot_path(backup_dir, entry)
        if not snapshot.is_dir():
            raise backup.BackupError(
                f"Restore point {entry.get('id')} is catalogued but its directory is"
                f" gone: {snapshot}"
            )
        manifest = backup.read_manifest(snapshot)
        selection = backup.resolve_selection(manifest, args.only) if args.only else None
    except backup.BackupError as exc:
        return _fail(exc)
    for warning in warnings:
        print(f"WARNING: {warning}", file=sys.stderr)
    print(f"SNAPSHOT\t{snapshot}")
    print(f"ID\t{entry.get('id')}")
    if selection is not None:
        # The teardown scope travels as its own line kinds rather than as extra
        # columns: bash reads artifact rows with `read -r kind archive target
        # owner`, which would fold a fifth column into $owner. Resolving it here
        # also keeps the compose parsing on the Python side of the split.
        print(f"PROFILES\t{','.join(selection.profiles)}")
        print(f"ADDONS\t{','.join(selection.addons)}")
        artifacts = selection.artifacts
    else:
        artifacts = backup.manifest_artifacts(manifest)
    for artifact in artifacts:
        try:
            backup.validate_target(artifact, config_dir)
        except backup.BackupError as exc:
            return _fail(exc)
        target = artifact.source
        if artifact.kind == "configdir":
            # Restore into the config dir the stack reads from *now*, not the
            # one recorded at backup time -- the snapshot may be replayed onto
            # a host that keeps its bundle somewhere else.
            target = str(config_dir)
        print(f"{artifact.kind}\t{artifact.archive}\t{target}\t{artifact.owner}")
    return 0


def cmd_restore_selectors(args: argparse.Namespace) -> int:
    """What a restore point offers a picker: SELECTOR<TAB>KIND<TAB>ARCHIVES<TAB>VOLUMES.

    Prints nothing for a v1 snapshot, which is the honest answer -- it carries
    no grouping, so it is restorable only as a whole."""
    config_dir = Path(args.config_dir)
    try:
        backup_dir = _resolve_backup_dir(config_dir, args.backup_dir)
        entry, _warnings = backup.resolve_restore_point(backup_dir, args.restore_point)
        manifest = backup.read_manifest(backup.snapshot_path(backup_dir, entry))
    except backup.BackupError as exc:
        return _fail(exc)
    for item in backup.selectors(manifest):
        print(
            f"{item['selector']}\t{item['kind']}\t{len(item['archives'])}"
            f"\t{','.join(item['volumes'])}\t{','.join(item['profiles'])}"
        )
    return 0


# ─────────────────────────────────────────────────────────────────────────
# upgrade
#
# The bash side owns every git call; these three commands own the version
# arithmetic and the migration ledger. Output is TSV for the same reason the
# backup commands use it -- `read` consumes it without a JSON parser.
# ─────────────────────────────────────────────────────────────────────────


def cmd_upgrade_resolve(args: argparse.Namespace) -> int:
    """Decide the target release from the tag list bash collected.

    STATUS is `up-to-date` when there is nothing to do (exit 0, the caller
    stops there) and `ok` otherwise. A downgrade is a refusal, not a status."""
    config_dir = Path(args.config_dir)
    repo_root = Path(args.repo_root)
    try:
        tags = Path(args.tags_file).read_text(encoding="utf-8").splitlines()
        versions = upgrade.parse_tags(tags)
        current = upgrade.resolve_current_version(config_dir, repo_root)
        target = upgrade.select_target(versions, args.version)
        status = upgrade.resolve_status(current, target, explicit=args.version is not None)
    except (upgrade.UpgradeError, OSError) as exc:
        return _fail(exc)
    print(f"CURRENT\t{current}")
    print(f"TARGET\t{target}")
    print(f"TAG\t{upgrade.tag_for(target)}")
    print(f"STATUS\t{status}")
    return 0


def cmd_upgrade_plan(args: argparse.Namespace) -> int:
    """List the migrations due for `--from` -> `--to`, in execution order.

    Reads them from --repo-root, which after the checkout is the *target*
    release's tree -- the only tree that carries the intermediate steps of a
    multi-release jump."""
    config_dir = Path(args.config_dir)
    try:
        found = migrations.discover(Path(args.repo_root))
        applied = migrations.applied_ids(migrations.load_state(config_dir))
        due = migrations.pending(found, args.from_version, args.to_version, applied)
    except ValueError as exc:
        return _fail(exc)
    for migration in due:
        # as_posix(): the consumer is bash, which under Git Bash cannot resolve
        # the backslash form a WindowsPath would render.
        print(
            f"MIGRATION\t{migration.id}\t{migration.version}"
            f"\t{migration.path.as_posix()}\t{migration.kind}"
        )
    return 0


def cmd_upgrade_record(args: argparse.Namespace) -> int:
    """Append one successfully applied migration to the ledger."""
    config_dir = Path(args.config_dir)
    try:
        found = {m.id: m for m in migrations.discover(Path(args.repo_root))}
        migration = found.get(args.migration_id)
        if migration is None:
            raise ValueError(f"Unknown migration: {args.migration_id}")
        migrations.record(config_dir, migration, duration_s=args.duration)
    except ValueError as exc:
        return _fail(exc)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="papaia-ctl-py")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--config-dir", required=True)
    sub = parser.add_subparsers(dest="command", required=True)

    p_materialize = sub.add_parser("materialize-core")
    p_materialize.set_defaults(func=cmd_materialize)

    p_defaults = sub.add_parser("defaults")
    p_defaults.set_defaults(func=cmd_defaults)

    p_localai_variants = sub.add_parser("localai-variants")
    p_localai_variants.set_defaults(func=cmd_localai_variants)

    p_setup = sub.add_parser("setup")
    p_setup.add_argument("--env", default="papaia")
    p_setup.add_argument("--host-ip")
    p_setup.add_argument("--app-host")
    p_setup.add_argument("--auth-host")
    p_setup.add_argument("--librechat-host")
    p_setup.add_argument("--litellm-host")
    p_setup.add_argument("--localai-host")
    p_setup.add_argument("--manager-host")
    p_setup.add_argument("--npm-admin-host")
    p_setup.add_argument(
        "--auth-provider", choices=["internal_keycloak", "external_oidc"], default=None
    )
    p_setup.add_argument("--oidc-issuer")
    p_setup.add_argument(
        "--reverse-proxy-provider",
        choices=["internal_nginx", "external_proxy", "no_proxy"],
        default=None,
    )
    p_setup.add_argument("--external-reverse-proxy", choices=["true", "false"], default=None)
    p_setup.add_argument("--enable-web-search", choices=["true", "false"], default=None)
    p_setup.add_argument("--enable-local-ai", choices=["true", "false"], default=None)
    p_setup.add_argument("--localai-variant", choices=list(gpu_detect.VARIANTS), default=None)
    p_setup.add_argument("--enable-manager", choices=["true", "false"], default=None)
    p_setup.add_argument("--reranker-model", default=None)
    p_setup.add_argument("--backup-dir", default=None)
    p_setup.add_argument("--allow-direct-port-access", action="store_true")
    p_setup.add_argument("--force", action="store_true")
    p_setup.set_defaults(func=cmd_setup)

    p_render = sub.add_parser("render")
    p_render.set_defaults(func=cmd_render)

    p_addon_install = sub.add_parser("addon-install")
    p_addon_install.add_argument("--name", required=True)
    p_addon_install.add_argument("--path", default=None)
    p_addon_install.add_argument("--version", default=None)
    p_addon_install.add_argument("--force", action="store_true")
    p_addon_install.set_defaults(func=cli_addon.cmd_addon_install)

    p_addon_start = sub.add_parser("addon-start")
    p_addon_start.add_argument("--name", required=True)
    p_addon_start.add_argument("--force", action="store_true")
    p_addon_start.set_defaults(func=cli_addon.cmd_addon_start)

    p_addon_check = sub.add_parser("addon-check")
    p_addon_check.add_argument("--target-core", default=None)
    p_addon_check.add_argument("--target-version", default=None)
    p_addon_check.add_argument("--target-addon-api", type=int, default=None)
    p_addon_check.add_argument("--target-min-addon-api", type=int, default=None)
    p_addon_check.add_argument("--json", action="store_true")
    p_addon_check.add_argument("--force", action="store_true")
    p_addon_check.set_defaults(func=cli_addon.cmd_addon_check)

    p_addon_remove = sub.add_parser("addon-remove")
    p_addon_remove.add_argument("--name", required=True)
    p_addon_remove.set_defaults(func=cli_addon.cmd_addon_remove)

    p_addon_uninstall = sub.add_parser("addon-uninstall")
    p_addon_uninstall.add_argument("--name", required=True)
    p_addon_uninstall.set_defaults(func=cli_addon.cmd_addon_uninstall)

    p_addon_networks = sub.add_parser("addon-networks")
    p_addon_networks.set_defaults(func=cli_addon.cmd_addon_networks)

    p_active_addons = sub.add_parser("active-addons")
    p_active_addons.set_defaults(func=cli_addon.cmd_active_addons)

    p_npm = sub.add_parser("npm-provision")
    p_npm.set_defaults(func=cmd_npm_provision)

    p_override_nets = sub.add_parser("override-external-nets")
    p_override_nets.add_argument("--file", required=True)
    p_override_nets.set_defaults(func=cmd_override_external_nets)

    p_addon_path = sub.add_parser("addon-path")
    p_addon_path.add_argument("--name", required=True)
    p_addon_path.set_defaults(func=cli_addon.cmd_addon_path)

    p_addon_override_files = sub.add_parser("addon-override-files")
    p_addon_override_files.add_argument("--name", required=True)
    p_addon_override_files.set_defaults(func=cli_addon.cmd_addon_override_files)

    p_backup_dir = sub.add_parser("backup-dir")
    p_backup_dir.add_argument("--backup-dir", default=None)
    p_backup_dir.set_defaults(func=cmd_backup_dir)

    p_backup_plan = sub.add_parser("backup-plan")
    p_backup_plan.add_argument("--backup-dir", default=None)
    p_backup_plan.add_argument("--existing-volumes", default=None)
    p_backup_plan.set_defaults(func=cmd_backup_plan)

    p_backup_finish = sub.add_parser("backup-finish")
    p_backup_finish.add_argument("--backup-dir", default=None)
    p_backup_finish.add_argument("--snapshot", required=True)
    p_backup_finish.add_argument("--result", choices=["ok", "partial", "failed"], default="ok")
    p_backup_finish.set_defaults(func=cmd_backup_finish)

    p_backup_prune = sub.add_parser("backup-prune")
    p_backup_prune.add_argument("--backup-dir", default=None)
    p_backup_prune.add_argument("--retention-period-days", type=int, required=True)
    p_backup_prune.set_defaults(func=cmd_backup_prune)

    p_backup_list = sub.add_parser("backup-list")
    p_backup_list.add_argument("--backup-dir", default=None)
    p_backup_list.set_defaults(func=cmd_backup_list)

    p_backup_delete = sub.add_parser("backup-delete")
    p_backup_delete.add_argument("--backup-dir", default=None)
    p_backup_delete.add_argument("--restore-point", action="append", required=True)
    p_backup_delete.set_defaults(func=cmd_backup_delete)

    p_upgrade_resolve = sub.add_parser("upgrade-resolve")
    p_upgrade_resolve.add_argument("--tags-file", required=True)
    p_upgrade_resolve.add_argument("--version", default=None)
    p_upgrade_resolve.set_defaults(func=cmd_upgrade_resolve)

    p_upgrade_plan = sub.add_parser("upgrade-plan")
    p_upgrade_plan.add_argument("--from", dest="from_version", required=True)
    p_upgrade_plan.add_argument("--to", dest="to_version", required=True)
    p_upgrade_plan.set_defaults(func=cmd_upgrade_plan)

    p_upgrade_record = sub.add_parser("upgrade-record")
    p_upgrade_record.add_argument("--migration-id", required=True)
    p_upgrade_record.add_argument("--duration", type=int, default=0)
    p_upgrade_record.set_defaults(func=cmd_upgrade_record)

    p_restore_resolve = sub.add_parser("restore-resolve")
    p_restore_resolve.add_argument("--backup-dir", default=None)
    p_restore_resolve.add_argument("--restore-point", default=None)
    p_restore_resolve.add_argument("--only", default=None)
    p_restore_resolve.set_defaults(func=cmd_restore_resolve)

    p_restore_selectors = sub.add_parser("restore-selectors")
    p_restore_selectors.add_argument("--backup-dir", default=None)
    p_restore_selectors.add_argument("--restore-point", default=None)
    p_restore_selectors.set_defaults(func=cmd_restore_selectors)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
