services:
  ###############
  #  LibreChat  #
  ###############
  librechat:
    container_name: librechat
    env_file:
      - ./.env
      - ../../.env
    ports:
      - "${LIBRECHAT_EXT_PORT}:${PORT}"
    depends_on:
      - lc-mongodb
      - lc-ragapi
    image: ghcr.io/danny-avila/librechat:v0.8.3
    restart: unless-stopped
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://lc-mongodb:27017/LibreChat
      MEILI_HOST: http://lc-meilisearch:7700
      RAG_PORT: ${RAG_PORT:-8020}
      RAG_API_URL: http://lc-ragapi:${RAG_PORT:-8020}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - lc-images:/app/client/public/images
      - lc-uploads:/app/uploads
      - lc-logs:/app/logs
      # - ./librechat/logo.svg:/app/client/dist/assets/logo.svg
      # - ./librechat/favicon-32x32.png:/app/client/dist/assets/favicon-32x32.png
      # - ./librechat/favicon-16x16.png:/app/client/dist/assets/favicon-16x16.png
    healthcheck:  # Defines the health check configuration for the container
      test: ["CMD-SHELL", "apk add --no-cache curl >/dev/null 2>&1 && curl -fs http://localhost:${PORT}/health || exit 1"]
      interval: 30s  # Perform health check every 30 seconds
      timeout: 10s   # Health check command times out after 10 seconds
      retries: 3     # Retry up to 3 times if health check fails
      start_period: 40s  # Wait 40 seconds after container start before beginning health checks
    networks:
      - default

  lc-mongodb:
    container_name: lc-mongodb
    env_file:
      - ./.env
    image: mongo:8.0.17
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - lc-mongodb:/data/db
    command: mongod --noauth
    networks:
      - default

  lc-meilisearch:
    container_name: lc-meilisearch
    env_file:
      - ./.env
    image: getmeili/meilisearch:v1.35.1
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      MEILI_HOST: http://lc-meilisearch:7700
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - lc-meilisearch:/meili_data
    networks:
      - default

  lc-vectordb:
    container_name: lc-vectordb
    env_file:
      - ./.env
    image: pgvector/pgvector:0.8.0-pg15-trixie
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${VECTORDB_NAME}
      POSTGRES_USER: ${VECTORDB_USER}
      POSTGRES_PASSWORD: ${VECTORDB_PASSWORD}
    volumes:
      - lc-vectordb:/var/lib/postgresql/data
    networks:
      - default

  lc-ragapi:
    container_name: lc-ragapi
    env_file:
      - ./.env
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: unless-stopped
    environment:
      DB_HOST: lc-vectordb
      RAG_PORT: ${RAG_PORT:-8020}
      POSTGRES_DB: ${VECTORDB_NAME}
      POSTGRES_USER: ${VECTORDB_USER}
      POSTGRES_PASSWORD: ${VECTORDB_PASSWORD}
    depends_on:
      - lc-vectordb
    networks:
      - default

# Volumes mounted on Windows: \\wsl.localhost\docker-desktop\mnt\docker-desktop-disk\data\docker\volumes
# Volumes mounted on Linux: /var/lib/docker/volumes
volumes:
  lc-images:
  lc-uploads:
  lc-logs:
  lc-mongodb:
  lc-meilisearch:
  lc-vectordb:
  lc-ragapi:

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
