services:
  ################################
  #  Jina AI compatible service  #
  ################################
  jina-reranker-api:
    image: ghcr.io/marko-boehm/jina-ai-litellm-reranker:latest
    container_name: jina-reranker-api
    restart: unless-stopped
    ports:
      - "${JINAAI_EXT_PORT:-8600}:8000"
    env_file:
      - ./.env
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
